# https://github.com/docker/setup-buildx-action
# https://github.com/marketplace/actions/docker-buildx
# https://github.com/crazy-max/diun/blob/master/.github/workflows/build.yml
name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout code
        uses: actions/checkout@v2
      - 
        name: Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.1
        with:
          buildx-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Run Buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 \
          -t mirrors2/liketriple:latest . --push
